<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') exit(1);
require_once __DIR__ . '/catalog.php';

try {
    $root = dirname(__DIR__, 2);
    $data = PortfolioMedia\compile("$root/public");
    if (in_array('--validate', $argv, true)) {
        fwrite(STDOUT, "Portfolio media: source data and all referenced assets validated.\n");
        exit(0);
    }
    $flags = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR;
    $source = "// Generated by npm run portfolio:compile. Edit public/portfolio/{video,short_film}/*.json instead.\n"
        . "import type {VideographyContent, ShortFilmsContent} from '../media';\n\n"
        . 'export const videography: VideographyContent = ' . json_encode($data['videography'], $flags) . ";\n\n"
        . 'export const shortFilms: ShortFilmsContent = ' . json_encode($data['short-films'], $flags) . ";\n";
    $directory = "$root/src/pages/portfolio/generated";
    if (! is_dir($directory) && ! mkdir($directory, 0777, true)) throw new RuntimeException('cannot create generated directory');
    $target = "$directory/media.ts";
    if (! is_file($target) || file_get_contents($target) !== $source) {
        $temporary = tempnam($directory, '.media-');
        if ($temporary === false) throw new RuntimeException('cannot create temporary output');
        try {
            if (file_put_contents($temporary, $source) === false || ! rename($temporary, $target)) {
                throw new RuntimeException('cannot write generated media');
            }
        } finally {
            if (is_file($temporary)) unlink($temporary);
        }
    }
    fwrite(STDOUT, "Portfolio media: compiled ordered Videography and Short Films content.\n");
} catch (Throwable $exception) {
    fwrite(STDERR, "Portfolio media compilation failed:\n" . $exception->getMessage() . "\n");
    exit(1);
}
